import Head from "next/head";
import Image from "next/image";
import SideBar from "../components/Sidebar";

export default function Home() {
  return (
    <div className="min-h-screen border border-transparent  bg-gray-800">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" mt-16 grid h-screen grid-cols-12 bg-gray-800 bg-opacity-95">
        <div className="col-span-2 border border-gray-700 bg-[#1F2937]">
          <SideBar />
        </div>
        <div className="col-span-10 grid grid-cols-3 gap-5 border border-gray-600 p-2">
          {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((x) => (
            <div className="relative">
              <Image
                src="https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cm9ib3RzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60"
                alt=""
                fill
              />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
